### ISSUE TITLE
why isn’t it that the creation and linking of all the components documented, but being launched from a cloud formation template?

### ISSUE THREAD

**Issue by naveenmarthala** [awslabs/amazon-sagemaker-mlops-workshop#13]
since this workshop is for beginners, wouldn’t it be the  proper approach to also teach (or at least document) how to create each component from CloudFormation stack individually rather than to just click a button and launch everything from a template and go on!!

or am i missing something here and ask this been documented somewhere?

**Comment by samir-souza** [comment]
This is a good point Naveen, but it is not the idea of this workshop to teach cloudformation. The main idea is to provide more abstract building blocks for the ML engineers to learn/customize this solution and build their own environment.

**Comment by naveenmarthala** [comment]
i didn't mean to expect the workshop to teach cloudformation. 

i wnated to convey that it would have been better to teach how to build each component of relevant service.

anyway,  got your point.
