### ISSUE TITLE
Access Denied from launching CloudFormation stack 

### ISSUE THREAD

**Issue by gucciwang** [awslabs/amazon-sagemaker-mlops-workshop#14]
Getting the following error when trying to launch the Cloudformation stack with the provided S3 URL `https://s3.amazonaws.com/aws-ai-ml-aod-latam/mlops-workshop/m.yml`. 

```S3 error: Access Denied For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html```

**Comment by samir-souza** [comment]
Fixed. Please try again.
