### ISSUE TITLE
AWS Lambda function upgrade to SageMaker SDK v2

### ISSUE THREAD

**Issue by dhawalkp** [awslabs/amazon-sagemaker-mlops-workshop#5]
The current lambda function code present in mlops_op_training.yml cloudformation template uses boto3 client to call sagemaker training jobs and other APIs of Sagemaker. Customers like to use SageMaker SDK to call SageMaker apis from Lambda function due to various reasons including simplicity of code, additional features present in high level SDK like sync/async calls etc. With the launch of SageMaker SDKv2, now its possible to add  SageMaker SDK library as part of lambda function due to its reduced package size.  Previously it was not possible to import due to SDK's package size was exceeding the 250Mb limit of lambda function. I will check-in the code with the changes in the aws lambda function using Sagemaker SDK v2. I will open the pull request and check-in the code in this repo. I am also writing a blog post on SageMaker SDK v2 features and benefits and will include this repo and change as part of this blog post as well.
Thanks

**Comment by samir-souza** [comment]
A new version with a simplified architecture, without lambdas, will be released soon! Thanks for the comment.
